varRefresh();
tempVar = calculateRandom(0,game.threatTracksSelecton.length - 1);
game.threatTracksSelecton[tempVar] = null;
game.threatTracksSelecton = cleanArray(game.threatTracksSelecton);
tempVar = calculateRandom(0,game.threatTracksSelecton.length - 1);
game.threatTracksSelecton[tempVar] = null;
game.threatTracksSelecton = cleanArray(game.threatTracksSelecton);
tempVar = calculateRandom(0,game.threatTracksSelecton.length - 1);
game.threatTracksSelecton[tempVar] = null;
game.threatTracksSelecton = cleanArray(game.threatTracksSelecton);
tempVar = calculateRandom(0,game.threatTracksSelecton.length - 1);
game.threatTracksSelecton[tempVar] = null;
game.threatTracksSelecton = cleanArray(game.threatTracksSelecton);
trace("===========================");
trace("zone0 - damage: " + game.ship[0].damage + " shield: " + game.ship[0].shields);
trace("zone1 - damage: " + game.ship[1].damage + " shield: " + game.ship[1].shields);
trace("zone2 - damage: " + game.ship[2].damage + " shield: " + game.ship[2].shields);
this.main.attachMovie("selectCrew","selectCrew",this.main.getNextHighestDepth());
this.main.selectCrew.attachMovie("playerSelect","playerSelect0",this.main.selectCrew.getNextHighestDepth());
this.main.selectCrew.playerSelect0._x = 500;
this.main.selectCrew.playerSelect0._y = 30;
this.main.selectCrew.playerSelect0.number = "1";
this.main.selectCrew.attachMovie("playerSelect","playerSelect1",this.main.selectCrew.getNextHighestDepth());
this.main.selectCrew.playerSelect1._x = 570;
this.main.selectCrew.playerSelect1._y = 30;
this.main.selectCrew.playerSelect1.number = "2";
this.main.selectCrew.attachMovie("playerSelect","playerSelect2",this.main.selectCrew.getNextHighestDepth());
this.main.selectCrew.playerSelect2._x = 640;
this.main.selectCrew.playerSelect2._y = 30;
this.main.selectCrew.playerSelect2.number = "3";
this.main.selectCrew.attachMovie("playerSelect","playerSelect3",this.main.selectCrew.getNextHighestDepth());
this.main.selectCrew.playerSelect3._x = 710;
this.main.selectCrew.playerSelect3._y = 30;
this.main.selectCrew.playerSelect3.number = "4";
this.main.selectCrew.attachMovie("playerSelect","playerSelect4",this.main.selectCrew.getNextHighestDepth());
this.main.selectCrew.playerSelect4._x = 780;
this.main.selectCrew.playerSelect4._y = 30;
this.main.selectCrew.playerSelect4.number = "5";
this.main.selectCrew.playerSelect4.gotoAndStop("on");
currentPlayerSelect = 4;
this.main.selectCrew.attachMovie("menu-crew-box","menu-crew-box0",this.main.selectCrew.getNextHighestDepth());
this.main.selectCrew["menu-crew-box0"]._x = 50;
this.main.selectCrew["menu-crew-box0"]._y = 150;
this.main.selectCrew["menu-crew-box0"].player = "CREW 1";
this.main.selectCrew["menu-crew-box0"].crewRank = game.tempCrewData[0].crewRank;
this.main.selectCrew["menu-crew-box0"].crewName = game.tempCrewData[0].crewName;
this.main.selectCrew["menu-crew-box0"].man.gotoAndStop(1);
this.main.selectCrew["menu-crew-box0"]["color-1"].gotoAndStop("off");
this.main.selectCrew["menu-crew-box0"]["color-2"].gotoAndStop("off");
this.main.selectCrew["menu-crew-box0"]["color-3"].gotoAndStop("off");
this.main.selectCrew["menu-crew-box0"]["color-4"].gotoAndStop("off");
this.main.selectCrew.attachMovie("menu-crew-box","menu-crew-box1",this.main.selectCrew.getNextHighestDepth());
this.main.selectCrew["menu-crew-box1"]._x = 241;
this.main.selectCrew["menu-crew-box1"]._y = 150;
this.main.selectCrew["menu-crew-box1"].player = "CREW 2";
this.main.selectCrew["menu-crew-box1"].crewRank = game.tempCrewData[1].crewRank;
this.main.selectCrew["menu-crew-box1"].crewName = game.tempCrewData[1].crewName;
this.main.selectCrew["menu-crew-box1"].man.gotoAndStop(2);
this.main.selectCrew["menu-crew-box1"]["color-0"].gotoAndStop("off");
this.main.selectCrew["menu-crew-box1"]["color-2"].gotoAndStop("off");
this.main.selectCrew["menu-crew-box1"]["color-3"].gotoAndStop("off");
this.main.selectCrew["menu-crew-box1"]["color-4"].gotoAndStop("off");
this.main.selectCrew.attachMovie("menu-crew-box","menu-crew-box2",this.main.selectCrew.getNextHighestDepth());
this.main.selectCrew["menu-crew-box2"]._x = 432;
this.main.selectCrew["menu-crew-box2"]._y = 150;
this.main.selectCrew["menu-crew-box2"].player = "CREW 3";
this.main.selectCrew["menu-crew-box2"].crewRank = game.tempCrewData[2].crewRank;
this.main.selectCrew["menu-crew-box2"].crewName = game.tempCrewData[2].crewName;
this.main.selectCrew["menu-crew-box2"].man.gotoAndStop(3);
this.main.selectCrew["menu-crew-box2"]["color-1"].gotoAndStop("off");
this.main.selectCrew["menu-crew-box2"]["color-0"].gotoAndStop("off");
this.main.selectCrew["menu-crew-box2"]["color-3"].gotoAndStop("off");
this.main.selectCrew["menu-crew-box2"]["color-4"].gotoAndStop("off");
this.main.selectCrew.attachMovie("menu-crew-box","menu-crew-box3",this.main.selectCrew.getNextHighestDepth());
this.main.selectCrew["menu-crew-box3"]._x = 623;
this.main.selectCrew["menu-crew-box3"]._y = 150;
this.main.selectCrew["menu-crew-box3"].player = "CREW 4";
this.main.selectCrew["menu-crew-box3"].crewRank = game.tempCrewData[3].crewRank;
this.main.selectCrew["menu-crew-box3"].crewName = game.tempCrewData[3].crewName;
this.main.selectCrew["menu-crew-box3"].man.gotoAndStop(4);
this.main.selectCrew["menu-crew-box3"]["color-0"].gotoAndStop("off");
this.main.selectCrew["menu-crew-box3"]["color-1"].gotoAndStop("off");
this.main.selectCrew["menu-crew-box3"]["color-2"].gotoAndStop("off");
this.main.selectCrew["menu-crew-box3"]["color-4"].gotoAndStop("off");
this.main.selectCrew.attachMovie("menu-crew-box","menu-crew-box4",this.main.selectCrew.getNextHighestDepth());
this.main.selectCrew["menu-crew-box4"]._x = 814;
this.main.selectCrew["menu-crew-box4"]._y = 150;
this.main.selectCrew["menu-crew-box4"].player = "CREW 5";
this.main.selectCrew["menu-crew-box4"].crewRank = game.tempCrewData[4].crewRank;
this.main.selectCrew["menu-crew-box4"].crewName = game.tempCrewData[4].crewName;
this.main.selectCrew["menu-crew-box4"].man.gotoAndStop(5);
this.main.selectCrew["menu-crew-box4"]["color-1"].gotoAndStop("off");
this.main.selectCrew["menu-crew-box4"]["color-2"].gotoAndStop("off");
this.main.selectCrew["menu-crew-box4"]["color-3"].gotoAndStop("off");
this.main.selectCrew["menu-crew-box4"]["color-0"].gotoAndStop("off");
colorSet = [];
mouseClick = false;
this.main.attachMovie("button","menuButton",this.main.getNextHighestDepth());
this.main.menuButton._x = 900;
this.main.menuButton._y = 600;
this.cursor.swapDepths(this.getNextHighestDepth());
